### ISSUE TITLE
Improve speed to tile loading for mapping

### ISSUE THREAD

**Issue by pmatos** [alex-hhh/ActivityLog2#28]
I did a 180k bike ride yesterday stretching several tiles. Loading more than 100 tiles is really slow. It takes patience to wait for it.
![2018-07-02-093228_1907x3483_scrot](https://user-images.githubusercontent.com/7911/42150696-dcea500a-7dda-11e8-830e-fd3e7f353654.png)

**Comment by alex-hhh** [comment]
Downloading tiles is slow.  There are several reasons for this: Racket HTTPS download seems to be slow, but OSM tile servers don't respond very fast either and I don't want to spend money on a key for mapping service.  You can also get your own free api key for Thunderforest, which has better download times (see https://github.com/alex-hhh/ActivityLog2/blob/master/doc/building.md for details).

The application implements caching of tile bitmaps, and the tiles are kept for 60 days, so if your activities are int he same geographic areas, the map drawing should be fast, as tiles are loaded from the local disk. Can you let me know if map drawing has improved after the tiles have been downloaded?

**Comment by alex-hhh** [comment]
By now, if you have used the application for a while and used to ride the same routes, the map tile cache should have been filled up and the map should load fast.  Let me know if this is not the case.

While it would be worthwhile to speed up the map tile download from the network, I do not have any time to work on this task...
