### ISSUE TITLE
Forcing import of activity causes other activities to disappear

### ISSUE THREAD

**Issue by pmatos** [alex-hhh/ActivityLog2#30]
I tried importing a large activity, which for some reason didn't seem to import. It was not shown in the activities tab. I then tried again but it said that it was already imported so I forced reimport.

After forcing the reimport the activity shows up in the activities tab, but older ones do not. Not sure what else I can add here to help with debugging, please let me know.

**Comment by alex-hhh** [comment]
First, I would like to make sure that all the activities are visible.  Can you make sure you have the **Activities** tab selected, as there is a **Last Import** tab, which only shows activities that were imported last.   Second, can you make sure you have the "All Sports" and "all days" selected in the filter, as the **Activities** tab will not show activities that don't match the filter, even if they were just imported.

<img width="281" alt="al2" src="https://user-images.githubusercontent.com/11592690/42153911-04206e16-7e17-11e8-88a3-61cb1ae1201b.png">

If the activities don't show up, we will need to look if they are in the database, I can help you out with that, if needed.

You can also check the log file, this is named **ActivityLogDbg.log** and should be placed in "~/.config/ActivityLog2" folder on Linux.  This might contain some information about the import.  If there were any errors during import, they should be listed in this file (although, the import dialog should also show the errors)

How large was the file you tried to import?  ActivityLog2 should be able to handle large files, although for activities longer than about 6 hours, things will get slower.

**Comment by pmatos** [comment]
Ah, yes that was the problem. The time period was not correctly set.
Do you have, in any case, a good viewer for the sqlite database? Do you use a gui of any sort you can recommend?

**Comment by alex-hhh** [comment]
This has happened to me several times before -- I started debugging the application, only to find that I did not set up the filter correctly.  I am open to proposals on how to improve the GUI, to prevent things like this...

As for sqlite, I just use the sqlite command line utility from Emacs.  I usually type the SQL queries in a separate buffer and type `C-c C-c` to execute the query.
