### ISSUE TITLE
Map is not centered

### ISSUE THREAD

**Issue by pmatos** [alex-hhh/ActivityLog2#31]
This is something I noticed earlier on both my machines. When I load the map for an activity, the map is not centered on screen. Here's a screenshot of how it's showing.
![2018-07-03-080814_1920x1080_scrot](https://user-images.githubusercontent.com/7911/42201456-430a728a-7e98-11e8-84a6-24e760a2927a.png)

**Comment by alex-hhh** [comment]
What happens if you click the "Fit to Window" button?

**Comment by pmatos** [comment]
That sorts it out. Should we emulate a fit to window call?

**Comment by alex-hhh** [comment]
This is already done as part of the `set-session` call:

https://github.com/alex-hhh/ActivityLog2/blob/master/rkt/session-inspector/inspect-map.rkt#L347

**Comment by alex-hhh** [comment]
Could you fetch the latest from master (I fixed a problem with the diagnostic drawing) and enable bounding box drawing code by evaluating the following code:

```racket
#lang racket
(require "rkt/utilities.rkt")
(put-pref 'activity-log:draw-track-bounding-box #t)
```

A box will be drawn on the map around the GPS track and a circle will be drawn in the center of the bounding box.   The circle should be in the middle of the map...

you can disable diagnostic drawing by passing `#f` to the `put-pref` command.

Thanks,
Alex.

**Comment by pmatos** [comment]
Where you do want me to evaluate the following code? Shall I add the code to `run.rkt`?

**Comment by alex-hhh** [comment]
You can just add it to a separate file and evaluate it, it will update the ActivtiyLog2 preferences file.

**Comment by alex-hhh** [comment]
Hi @pmatos , any updates on this issue? Thanks, Alex.

**Comment by alex-hhh** [comment]
Closing issue as no response was received in a long time and I cannot reproduce the problem myself so I cannot make any progress on it.  Will reopen it if I receive further information about it.
