### ISSUE TITLE
Wunderground stopped providing free API keys

### ISSUE THREAD

**Issue by pmatos** [alex-hhh/ActivityLog2#33]
`building.md` mentions one should get a Wunderground API key for weather, however as of May 15, 2018, Wunderground stopped providing free keys.

Complete announcement is here: https://www.wunderground.com/weather/api/ 

> To improve our services and enhance our relationship with our users, we will no longer provide free 
> weather API keys as part of our program. If you have been directed to download our Weather 
> Underground free API key by a third party provider, please contact your vendor for resolution.

This is very annoying, I wonder if there's an alternative service one can use.

**Comment by pmatos** [comment]
OK, darksky.net seems to be a free alternative to wunderground. I will see how hard it is to integrate alongside wunderground.

**Comment by alex-hhh** [comment]
Bummer! I will need to find another weather data provider (my own key appears to still work, they have not revoked it yet).  The code is in "rkt/weather.rkt", but it is a bit specific to Wunderground, and some effort will be required to make it generic.  Alternatively, we could simply switch to another provider, as I don't see a reason to support multiple ones.

**Comment by pmatos** [comment]
I will probably take a look a this after getting stryd to work if you have no time.
It seems this was a result of the IBM acquisition. darksky.net has a good weather api has well.

**Comment by alex-hhh** [comment]
Looks like darksky.net requires a Credit Card even if it will not be charged (the first 1000 calls / day are free).  Also, they prohibit encouraging users to sign up for API keys themselves.  

Currently the built version of ActivityLog2 bakes the Wunderground API key into the executable, so users don't have to get another API key.

There is also openweathermap.org which offers free API keys, but they don't offer historical data with the free API key -- this is needed as users might import activities that are several days old.

**Comment by pmatos** [comment]
argh, bummer. Other project relying on weather data apis must have found a solution already. Will take a look.

**Comment by alex-hhh** [comment]
I changed the weather service provider to DarkSky.net, and updated the build instructions on how to set up the key for the service.  Feel free to test this, when you have time.  I should release a new version of ActivityLog2 as well with a new API key built in.
