### ISSUE TITLE
segfault when choosing File -> Import

### ISSUE THREAD

**Issue by simendsjo** [alex-hhh/ActivityLog2#39]
I'm on NixOS

```
$ racket --version
Welcome to Racket v7.1.
$ git clone ...
$ racket build.rkt # Couldn't find glib, and didn't want to mess with nix-shell
$ racket run.rkt # Chose File -> Import
SIGSEGV MAPERR si_code 1 fault on addr (nil)
[1]    18806 abort      racket run.rkt
```

**Comment by simendsjo** [comment]
Nevermind. I get the same result when trying to open anything in DrRacket, so I guess it's something about my racket install.

**Comment by alex-hhh** [comment]
If you fix your Racket installation on NixOS (and get ActivityLog2 to work), could you add an explanation of your solution to this issue, to help other people encountering the same problem?

Thanks,
Alex.

**Comment by simendsjo** [comment]
It was a bug in the package description in Nix. It's been fixed here https://github.com/NixOS/nixpkgs/pull/54163.

**Comment by simendsjo** [comment]
I can verify that it works now.
