### ISSUE TITLE
HiDPI support?

### ISSUE THREAD

**Issue by simendsjo** [alex-hhh/ActivityLog2#40]
This might actually be a racket issue. It seems like some components scale correctly, and others don't

![2019-01-18-180150_1199x595_scrot](https://user-images.githubusercontent.com/351519/51401568-5e4b4880-1b4b-11e9-9739-09a45f5c0e0d.png)

**Comment by alex-hhh** [comment]
I also use a HiDPI display, and the elements look proportional, but in your screenshot it looks like the standard elements are scaled a lot more than on my system.

In any case, for some elements, which are not standard GUI elements, the application creates its own fonts.  Currently you will need to edit the size of these fonts manually by searching for `find-or-create-font` method calls in the code base.  In the screenshot you attached, you adjust the size of the left tab bar and the activity type text at the following locations:

https://github.com/alex-hhh/ActivityLog2/blob/afb4a0dda1b738ab6404dd37ce8afd50c9104bd4/rkt/widgets/tab-selector.rkt#L48

https://github.com/alex-hhh/ActivityLog2/blob/afb4a0dda1b738ab6404dd37ce8afd50c9104bd4/rkt/workout-editor/workout-editor-headline.rkt#L23

**Comment by alex-hhh** [comment]
Looking at the screenshot again, it seems you highlighted the directory selection dialog -- this is built-in in Racket, so fixing the "Filename" label would require a change to Racket.  Interestingly, the fonts in this dialog scale fine on HiDPI on Windows.

If you want to modify this application to suit your needs, I can point you in the right direction and if you submit the changes back as a pull request, I will consider them.  Also, ActivityLog2 is a hobby project -- I don't have the time and resources to test and tweak the application on all platforms where it might be used, but I will consider all bug reports and enhancement proposals I receive.

**Comment by simendsjo** [comment]
Looks like an issue with GTK3. I scale X and fonts using `X -dpi` and `Xft.dpi`. Looks like some parts of GDK doesn't some to honor these settings and rather uses pixel (my guess).
But if I override GDK_SCALE and GDK_DPI_SCALE, setting GDK_SCALE to my `-dpi` scaling and reversing my `Xft.dpi` using GDK_DPI_SCALE, I get correct results.

So my DPI was 96. I set -dpi and Xft.dpi to 192. Then setting GDK_SCALE to 2 and GDK_DPI_SCALE to 0.5, I get the following for ActivityLog2:

![2019-01-20-093126_1831x1031_scrot](https://user-images.githubusercontent.com/351519/51436920-35839a00-1c96-11e9-8c02-a2fa9f00b218.png)

I'll set this system wide and see if this breaks other applications.

**Comment by simendsjo** [comment]
.. closing this as it was totally unrelated to ActivityLog or Racket
