### ISSUE TITLE
Issue creating workout

### ISSUE THREAD

**Issue by allanw** [alex-hhh/ActivityLog2#47]
I downloaded release 1.8.2 and tried running it on a Mac using the `racket run.rkt` command. The application loads and I can import an activity, but when I go to the 'Workouts' section I can't seem to create a workout - am I doing something wrong? Please see the screenshot attached.

![Screen Shot 2020-05-12 at 3 29 20 pm](https://user-images.githubusercontent.com/237499/81642041-ca02a480-9465-11ea-9274-caf206e015f0.png)

**Comment by alex-hhh** [comment]
You can create a new workout by selecting the "Workout / New Workout" menu item, but I should probably add a "New Workout" button somewhere.

**Comment by alex-hhh** [comment]
Hopefully my previous message addressed your question.  I will close this issue, but add another comment or create a new issue if you have further questions or find any bugs.
