### ISSUE TITLE
can't import workout files from garmin forerunner 245 device

### ISSUE THREAD

**Issue by ericJrdn** [alex-hhh/ActivityLog2#49]
Hi,
Please find perfectly valid workout files from a garmin forerunner 245 device.
They give the following error message in a console window opened by the software when I try to import it:
[Workouts.zip](https://github.com/alex-hhh/ActivityLog2/files/5286518/Workouts.zip)

dict-ref: no value for key: 'duration-value in: '((target-value . 0) (8 . #"") (message-index . 0) (name . #"") (duration-type . open) (target-type . open) (intensity . warmup))

observed with ActivityLog2 version 1.10.0.547

**Comment by alex-hhh** [comment]
Thanks for reporting this -- there was a problem with importing workouts which had steps which require pressing the Lap button.  This is now fixed and I released a new version at https://github.com/alex-hhh/ActivityLog2/releases/tag/v1.10.1, can you please try it out.

**Comment by ericJrdn** [comment]
It seems ok, thank you.

Tested:
- import -> display my workout files
- import -> export -> import
- create and configure -> export to device -> display on device

Thank you
Eric
