### ISSUE TITLE
Failed to import

### ISSUE THREAD

**Issue by Wanted135** [alex-hhh/ActivityLog2#50]
Hey, when trying to import a .fit file I get this error :

Failed to import C:\Users\Wanted\Downloads\50_minutes.fit: #(struct:exn:fail:contract hash-ref: no value found for key
  key: 143 #<continuation-mark-set>)

Thank you.

**Comment by alex-hhh** [comment]
Can you share that activity, so I can have a look? Either attach it to this issue, or send it to me directly at AlexHarsanyi@gmail.com. I have a large collection of "odd" FIT files for testing, but it seems that there is always a new one, which breaks...

**Comment by Wanted135** [comment]
> Can you share that activity, so I can have a look? Either attach it to this issue, or send it to me directly at [AlexHarsanyi@gmail.com](mailto:AlexHarsanyi@gmail.com). I have a large collection of "odd" FIT files for testing, but it seems that there is always a new one, which breaks...

sent !

**Comment by alex-hhh** [comment]
Thanks for reporting this.   The FIT file recorded by your device contains 64 bit data types, and these were not supported.  I have added support for them, and I will need to do some more testing, but I am hoping to release a fix for this over the weekend.

**Comment by Wanted135** [comment]
Thanks

**Comment by alex-hhh** [comment]
I released an updated version of the application, which should fix the issue.  You can download it from here: https://github.com/alex-hhh/ActivityLog2/releases/tag/v1.10.2, let me know if it fixes the problem.

**Comment by Wanted135** [comment]
Thank you so much, will try it ASAP

**Comment by Wanted135** [comment]
It is working perfectly, thank you again for the quick fix, cheers !
