### ISSUE TITLE
Incorrect ascent/descent calculation?

### ISSUE THREAD

**Issue by misev** [alex-hhh/ActivityLog2#51]
ActivityLog2 calculates disproportionately large ascent/descent values for my runs which are typically very flat otherwise. I have Garmin 910xt watch with barometric altimeter.

I'll try to illustrate the problem on a 2km run, for which ActivityLog calculates 58m elevation gain, although in reality there should be no more than 1-2 meter change. There are two Elevation (m) charts:

1. I think this is the correct one, as the real elevation is around 1m:
![Screenshot_20201101_215858](https://user-images.githubusercontent.com/4786324/97815327-742ced80-1c8d-11eb-846d-c38acb001bd8.png)

2. Presumably this one comes from the barometric measurements:
![Screenshot_20201101_220004](https://user-images.githubusercontent.com/4786324/97815352-9aeb2400-1c8d-11eb-9a76-369223ced05f.png)

I'm guessing ActivityLog2 takes 2. for the ascent/descent calculation. Is it possible to influence this?
I'm not sure why it is so wacky even though it's from a flat road, possibly the sensor is broken as it's a pretty old watch.

Thanks

**Comment by alex-hhh** [comment]
Elevation Correction is one of the topics on which I spent a lot of time and I am still now 100% happy with the overall results.  There are several issues raised in your comment and I will try to address them separately.

**First**, I think you may have the graphs the wrong way around.  The first graph (dark green) is the data that is recorded by your device and the second one is the corrected elevation produced by AL2.  If you want to be absolutely sure, you can change their names here (the second one is what AL2 calculates):

https://github.com/alex-hhh/ActivityLog2/blob/adf8d16969ab4d3c1687cce906a6e27864596a43/rkt/session-df/native-series.rkt#L438

https://github.com/alex-hhh/ActivityLog2/blob/adf8d16969ab4d3c1687cce906a6e27864596a43/rkt/session-df/native-series.rkt#L459

**Second**, regarding the 58 meter altitude gain, the altitude gain is measured as the sum of the ascent segments, so, if you climb 10 times a hill with 2 meter elevation, the altitude gain is 20 meters.  Looking at both graphs and adding the elevation gain for just some of the segments will already get you past the 1-2 meter changes you mention.

It is difficult to determine which graph is more correct.  I suspect you started and finished the run in the same place, so the uphill trend in the original data is probably incorrect.  I am not sure how correct the second graph is though, but given that the altitude is in the 5-15 meter range, it is probably averaging altitudes from other runs you did on the same route (see notes below).

## So what are the options

Both the original and the corrected elevation is stored for each data point, so you can choose which plot to display (although the names could be updated to be different).  However, summary data is only stored in one place, so the min/max/total ascent/total descent values are only stored in one place for each lap and the session itself and this is calculated from the corrected elevation.

For one-off sessions where you don't want corrected elevation, you can clear the corrected elevation from the "Activity / Clear corrected elevation ... " menu.  This will clear the corrected elevation and re-calculate summary values from the original data that was recorded by the device.

To disable the corrected elevation altogether for all newly imported activities, you will need to comment out this line from the source code:

https://github.com/alex-hhh/ActivityLog2/blob/adf8d16969ab4d3c1687cce906a6e27864596a43/rkt/import.rkt#L65

## Some more details

The algorithm used by ActivityLog2 for correcting the elevation is based on averaging the elevation for a given GPS coordinate based on several runs that pass over the area. If you run the same route (or part of it) multiple times, the elevation will be the average elevation across all those runs.

The implementation details are somewhat complex and you can find them here: https://github.com/alex-hhh/ActivityLog2/blob/master/rkt/models/elevation-correction.rkt

I found that this algorithm produces good results if you run or cycle the same routes, but it behaves somewhat poorly if there is only a small amount of data and the route is mostly flat.  However, even barometric sensors have a lot of error in their measurements: https://alex-hhh.github.io/2020/08/barometric-altitude-measurement.html

Over the years, I keep refining this algorithm and currently I am working on some changes which would filter out outliers data from previous routes, this will be ready by the end of this week (hopefully).

Perhaps one of the big gaps in managing corrected elevation is that, so far, I didn't receive any feedback from others, so this algorithm, and the user interfaces around it, reflects the data that I have (although I do have a fair amount of running, cycling, hiking and skiing activities).  I am happy to provide any more clarifications about the algorithm and, if you have any feedback about it, I am happy to consider it.

**Comment by misev** [comment]
> First, I think you may have the graphs the wrong way around.

Ah this is indeed right, I did "Clear corrected elevation" and the second graph disappeared. I didn't realize that ActivityLog2 does the elevation correction automatically.

I think the profile *shape* of the graph produced by ActivityLog2 is a bit more correct, but it looks too noisy with way too big ups and downs, on a very flat road with about maybe 2-3 meters altitude difference between the ends.

Here's another one from one lap on a standard 400m track which is at altitude 3 meter above sea level:
![Screenshot_20201102_094443](https://user-images.githubusercontent.com/4786324/97847584-24334280-1cf0-11eb-98d6-312ff33f059a.png)
![Screenshot_20201102_094511](https://user-images.githubusercontent.com/4786324/97847595-28f7f680-1cf0-11eb-8511-4b741abb3aa4.png)

> the altitude gain is measured as the sum of the ascent segments

Yes I understand this, but the watch data is definitely a bit noisy. Maybe the vertical body+arm movement influence it. I suspect that changes within 1 meter or so may need smoothing? Looks like a difficult problem to do correctly though.

Thanks for the hint on how to disable the auto correction, I'll do this as it doesn't seem to work very well in my case. My routes are indeed mostly flat. Compared to Garmin connect, the elevation gain can be 30-40x higher in ActivityLog2.

Have you considered additionally using elevation data like SRTM or so? The freely available data is usually not so high resolution, typically 30 meters, but it should be sufficient to add additional accuracy to the barometer data. The problem is that world coverage is rather large, 100+ GB, so it's tricky to use from a desktop application.

**Comment by misev** [comment]
> The problem is that world coverage is rather large, 100+ GB, so it's tricky to use from a desktop application.

Using some free API could be a solution, e.g. [Bing maps](https://docs.microsoft.com/en-us/bingmaps/rest-services/elevations/?toc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fbingmaps%2Frest-services%2Ftoc.json&bc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2FBingMaps%2Fbreadcrumb%2Ftoc.json), although it adds complexity with regards to privacy.

**Comment by alex-hhh** [comment]
I probably spent more time on elevation correction than any other feature and my conclusion is that using an offline solution is the only viable option for this project, given that I am a single developer and I work on this project in my spare time.

I want to avoid using an external API as they tend to change and I can easily spend all my time on maintaining these API connections.   My experience with weather APIs (#46) has not been very positive in this regard.

Downloading STRM tiles is also not a good option -- this data is 2 Gb in size and that is a large amount of data to carry around for a small feature.
 
I am constantly tweaking this algorithm (and working on a set of tweaks now), but it will always have some limitations.  My aim is to get it to work well for sessions where there is a lot of data available (i.e. running on the same routes) and where there is a significant amount of elevation change (e.g. hiking and skiing activities).  I will also add a preferences option to disable calculating corrected elevation on import, to allow users to disable the feature.

----

Also, if some of your runs are on a track (where the elevation gain and loss is zero), you might want to consider changing the sport type to "Track Running" and just removing the elevation plots from the Charts view -- ActivityLog2 maintains the chart view configuration on a per-sport basis, so you can have the normal runs show the elevation, while the track runs won't.    You can also select what columns are visible in the Laps tab, and these are also remembered per sport type.

This is not ideal, as the map view will still show elevation and you will still have elevation gain shown in the overview tab.

**Comment by misev** [comment]
I fully agree about the 3rd party API. And using SRTM data is very similar to the external API idea too, although at least there are no worries about privacy and it's unlikely the source will be taken down.

Thanks for the hint about the track, I didn't realize there such a sport type!

Unfortunately I haven't found much time to put into learning Racket, which is completely different to the stuff I know (C++ mainly). As soon as I get better at it I'll gladly contribute some code. Especially on Linux there are small things I'd like to fix to improve the UX a bit (stuff like keyboard shortcuts for copy/paste, better font size for 4k resolution, and such). Regardless, I find ActivityLog2 rock solid, and I'm surprised it doesn't have more widespread use!

Back on topic, as far as I'm concerned this question can be closed. Up to you.

**Comment by alex-hhh** [comment]
I will keep this issue open a little longer, since I will have some corrected elevation improvements done shortly and I might as well link them here (in particular, I will add a configuration option for disabling elevation correction on import).

For other improvements that you are thinking about, it would be good if you could create separate issues for them -- it will at least give me some ideas of what would be needed, especially since I only run the application on Windows, it would be good to get some feedback from Linux users.  Also, if the changes they are simple enough I might end up doing them, or I can show you how to address them -- making simple changes does not require much Racket knowledge, you only need to know where to make the modification.

**Comment by alex-hhh** [comment]
Hi @misev , I made some changes to the elevation correction algorithm:

* first, you can now disable the elevation correction for imported activities from the "Edit/Preferences..." menu.  Even if you disable it, you can still fix elevation and/or clear elevation for individual activities
* the summary values  (total ascent, total descent) calculation has been changed to be less sensitive to small amounts of elevation change making the result more conservative
* the elevation line itself will be less smoothed not and small local changes in elevation will be preserved.

I don't think this will work perfectly for track data, although perhaps it will be more closer to reality, especially if you accumulate more data.

----

If you want to update your repository, please be aware that dependent submodules have been changes, and you will need to run the following commands after fetching the changes and before you build the new version:

```
git submodule foreach git fetch
git submodule update
```

**Comment by misev** [comment]
Great, I think it works quite better now. It's ok to close the issue from my side.

**Comment by alex-hhh** [comment]
It is good that it is working better for you now (I only have my own activities to make judgments on how good an algorithm is).  There is one last bit that I want to do as part of this issue, which is to delete a database index which is no longer used.  This index accounts for about 15% of the size of the database and was only used by the previous elevation correction algorithm.  Hopefully I'll get to it sometimes next week.
