### ISSUE TITLE
Add labels to the activities view

### ISSUE THREAD

**Issue by idealist1508** [alex-hhh/ActivityLog2#61]
I really like labels in ActivityLog2. Usability of labels can be further improved by displaying them in table on activities view:
![grafik](https://user-images.githubusercontent.com/4608274/109419589-81a17c80-79ce-11eb-9f00-d44aee4b27dc.png)
What do you think? I could try to implement this and make PR.

**Comment by idealist1508** [comment]
How do you run test? Do you use code coverage?

**Comment by alex-hhh** [comment]
Implementing this task requires familiarity with both SQL and Racket.   I don't have time to work on it in the short to medium term, but if you want to give it a go, here is what needs to be done:

* Update the [V_ACTIVITY_LIST](https://github.com/alex-hhh/ActivityLog2/blob/391bf2b1cc2cc101149e1d0a093ae332bab8cf06/sql/db-schema.sql#L1192) view to include an entry for the labels from the [SESSION_LABEL](https://github.com/alex-hhh/ActivityLog2/blob/391bf2b1cc2cc101149e1d0a093ae332bab8cf06/sql/db-schema.sql#L1042) table.  This needs to be a database migration, as explained in the [database notes](https://github.com/alex-hhh/ActivityLog2/blob/master/docs/database.md).
* add an entry for the new column of the view to [*activity-list-display-columns*](https://github.com/alex-hhh/ActivityLog2/blob/391bf2b1cc2cc101149e1d0a093ae332bab8cf06/rkt/view-activities.rkt#L308)
* update the [set-session-tags](https://github.com/alex-hhh/ActivityLog2/blob/391bf2b1cc2cc101149e1d0a093ae332bab8cf06/rkt/al-widgets.rkt#L231) method to also post an `session-updated` event that the session ID has changed, as explained in [gui-consistency.md](https://github.com/alex-hhh/ActivityLog2/blob/master/docs/gui-consistency.md) -- this will ensure that the entry in the list is updated when the user edits the labels.

In practical terms, you want to first back up your database, than update V_ACTIVITY_LIST directly using any SQLite tool -- I am using the sqlite command utility from Emacs.  This will allow to experiment with the view creation code and the rest of the Racket changes before you write the database migration.

-----

With regards to the test suite, the tests are in the `tests/` sub-folder, and you can run them using commands such as "raco test tests/db-test.rkt".   Note however that some tests require data which is private (my own training data), as such, while they will run on your machine, you won't be able to actually test anything.    This is explained in the [README.md](https://github.com/alex-hhh/ActivityLog2/blob/master/docs/README.md#test-suite) document.

There is no test coverage set up.

**Comment by alex-hhh** [comment]
Thanks for working on this feature.  I now merged the pull request, and will close this issue.
