### ISSUE TITLE
Map widget opens too many connections ins internet.

### ISSUE THREAD

**Issue by idealist1508** [alex-hhh/ActivityLog2#68]
To reproduce: 
* open map view with a long ride.   
* set a maximal zoom
* move a mouse in a bottom graph from left to right.
=> ActivityLog2 makes too many connections.  
![grafik](https://user-images.githubusercontent.com/4608274/116719426-55f53f80-a9db-11eb-9c6b-c3c1e8c4f44a.png)

**Comment by idealist1508** [comment]
I couldn't explain why it doesn't work with net/url.
After I changed it to http-easy, only 2 connections are used. Please look at  https://github.com/idealist1508/map-widget/commit/34d078378a0ec04547c551e954db69dc892a1135
Should I make a PR for this?

**Comment by alex-hhh** [comment]
Yes, can you please create a PR for this?  I don't know much about fetching data over HTTP, so I just used the default available (also, http-easy was not available when I wrote this code.   I will mention this problem on the Racket user lists, maybe the built-in library can also be fixed...
