### ISSUE TITLE
division by zero

### ISSUE THREAD

**Issue by ericJrdn** [alex-hhh/ActivityLog2#73]
Hi,
Please find a .fit file that throws a division by zero error when opening the laps view.
[2021-07-14-16-40-18.zip](https://github.com/alex-hhh/ActivityLog2/files/6818391/2021-07-14-16-40-18.zip)

**Comment by alex-hhh** [comment]
Thanks for reporting this.  I pushed a fix to the master branch.  If you are using Windows, there is a pre-built binary with this fix here: https://dev.azure.com/alexharsanyi0641/ActivityLog2/_build/results?buildId=867&view=artifacts&pathAsName=false&type=publishedArtifacts
