### ISSUE TITLE
Heart rate data is lost after joining or splitting a swim lap.

### ISSUE THREAD

**Issue by idealist1508** [alex-hhh/ActivityLog2#79]

**Comment by alex-hhh** [comment]
Hi @idealist1508 , I attempted to fix this issue in the following branch: https://github.com/alex-hhh/ActivityLog2/tree/ah/pr79-a

Can you give it a try and see if it works for you?  I would recommend you backup your database first...

**Comment by idealist1508** [comment]
Awesome! Works! 
I tested it in DB with only one Activity. I have not noticed any problems in db.
