### ISSUE TITLE
Error in Edit Swim lap

### ISSUE THREAD

**Issue by idealist1508** [alex-hhh/ActivityLog2#84]
I got an error after joining 3 laps to one.
```
query-row: cannot convert given value to SQL type
  given: #f
  type: parameter
  dialect: SQLite
  context...:
   .../generic/interfaces.rkt:209:0: error*
   .../sqlite3/dbsystem.rkt:35:0: check-param
   .../generic/prepared.rkt:90:0: apply-type-handlers
   .../generic/prepared.rkt:70:4: bind method in prepared-statement%
   .../generic/functions.rkt:110:0: query-row*
   .../private/arrow-val-first.rkt:486:18
   .../dialogs/edit-lap-swim.rkt:808:0: fetch-length-data
   .../dialogs/edit-lap-swim.rkt:983:0: join-lengths
   .../dialogs/edit-lap-swim.rkt:1204:3
   .../generic/functions.rkt:187:2
   .../dialogs/edit-lap-swim.rkt:778:4: begin-edit method in lap-swim-edit%
   .../dialogs/activity-edit.rkt:182:4: on-edit-lap-swim
   .../private/mrmenu.rkt:250:14: command method in basic-selectable-menu-item%
   .../private/more-scheme.rkt:148:2: call-with-break-parameterization
   .../unsafe/atomic.rkt:73:13
   .../common/queue.rkt:435:6
``` 

to reproduce:

- open "edit lap swim" window with min. 3 lengths
- select first length and click join with next
- select third length and click join with prev
- click save

**Comment by alex-hhh** [comment]
The lap swim editor cannot handle joining multiple lengths and tries to disable the various join buttons to prevent the user from doing that... Looks like this is a use case I missed, I'll look at the code to disable the "Join with prev" button in this case.

**Comment by alex-hhh** [comment]
I pushed a fix for this issue, to disable the join button and disallow joins with lengths that were already joined.  The error will no longer happen.   Unfortunately, the lap swim editor would require a redesign to allow merging multiple lengths in one go, however, you can merge two of them, save the activity and re-open the lap swim editor to merge again.
