### ISSUE TITLE
Workout files don't appear anymore on the watch after copying to Newfiles

### ISSUE THREAD

**Issue by JoopVerdoorn** [alex-hhh/ActivityLog2#86]
Hi Alex, 
I have been using your app during the lockdowns to distribute intervaltrainings in fit file form to other runners in our athletic club. Unfortunately now (with a new lockdown in the Netherlands) the workouts don't show up in all Garmin watches anymore. A recent workout fit file, exported from the latest Windows version of Activilog2 (download from releases page), did work on a Vivoactive 3, but not on my Fenix 6 pro. It did use to work. This could be due to a firmware problem of course, but I have no other options to test that. Did you change anything in the fit-file format?
PS: I am a developer for Garmin datafields (Datarun premium for example).
Regards,
Joop

**Comment by JoopVerdoorn** [comment]
Sorry, it is probably something with the watch. I remembered that the Fit file repairtools also had an option to create a workout fit file and when I added a workout fit file to the watch from these tools the workout created with Activitylog2 appeared as well

**Comment by alex-hhh** [comment]
There have been no changes to the workout FIT file creation code and I also tested creating a workout and it worked correctly for the FR945 (the unit that I have).  

There could be a possibility that some workout steps are incorrectly encoded, so if you notice any problems it would be a good idea to attach the FIT workout that is causing problems and I could have a look.
