### ISSUE TITLE
Humindex

### ISSUE THREAD

**Issue by fnordson** [alex-hhh/ActivityLog2#87]
AL Version:  2022.01 build #1059

Could someone elaborate on the "humindex" measurement? 
According to Wikipedia https://en.wikipedia.org/wiki/Humidex it should be a value somewhere above 10. 
However my stats show this: 

![grafik](https://user-images.githubusercontent.com/5624605/152698868-7cee575f-0f93-4d61-b881-c42d595a4f68.png)

Those values would rather fit to the average actual temperature. 
So is humindex in AL = actually average temperature or is it broken?

**Comment by alex-hhh** [comment]
The Humidex calculation is done in the link shown below.  It was based on the formula from a web page which no longer exists, but the formula is the same as the one on Wikipedia, except for some small precision differences on some of the constant factors:

https://github.com/alex-hhh/ActivityLog2/blob/f1cc8d98c47b1fa11db08c4f2413b1308de9750a/rkt/weather.rkt#L60

The formula itself has no limit for 10 degrees and can produce values below 10 degrees.  I also could not find where on the Wikipedia page it states that the values should always be above 10?  They provide a table at the end, but this is just some sample ranges that they have chosen, unless I am misunderstanding something?

**Comment by fnordson** [comment]
I didn't get the formula but thanks for the explanation. 
I get it now.  
Yeah, weather was really shitty.
