### ISSUE TITLE
gdi32.dll on win 7

### ISSUE THREAD

**Issue by studiosacchetti** [alex-hhh/ActivityLog2#92]
hello
after installing latest version program wont start and show this error. os is win7/64

![Appunti01](https://user-images.githubusercontent.com/33520105/194007599-0554955e-0595-4463-bd63-dff5302832cf.jpg)

regards

**Comment by alex-hhh** [comment]
This looks like a problem with Racket itself (which is the programming language used for this project), more specifically, the Windows build of libpango, possibly the same issue as described here: https://github.com/viking-gps/viking/issues/136

**Comment by alex-hhh** [comment]
This was a Racket issue, which was fixed in version 8.9, the latest ActivityLog2 release (2023.07) uses this Racket version for the build, so the issue should be fixed.

For more details about the issue, see https://racket.discourse.group/t/does-drracket-8-7-start-on-windows-7/1637/10
