### ISSUE TITLE
Fix overflowing text boxes on MacOS

### ISSUE THREAD

**Issue by jerome-tgl** [alex-hhh/ActivityLog2#97]
Bug report: all text input fields overfill their container from bottom-left corner.

This hides the rest of the container and make other components inaccessible with pointing devices.

# Screenshots

Activities:
<img width="1304" alt="Activities" src="https://github.com/alex-hhh/ActivityLog2/assets/8667221/6308171f-842b-47b0-b0d1-4865937bb643">

Trends:Setup…:

<img width="463" alt="Trends:Setup…" src="https://github.com/alex-hhh/ActivityLog2/assets/8667221/6b05ab69-d4f6-46c9-a23b-0fa72c92e5ad">

New athlete metrics…:

<img width="449" alt="New athlete metrics…" src="https://github.com/alex-hhh/ActivityLog2/assets/8667221/ac04e53e-9781-4d3b-8861-31f12033057b">

# Debug info
- System: macOS 14.2.1
- ActivitLog2: 2024.01.99
- Racket version: 8.11.1

**Comment by alex-hhh** [comment]
Thanks for reporting this. This looks like a bug, but unfortunately, I don't have access to a MacOS computer.  

This problem does not happen on Windows or Linux (I verified this), so it looks like it is specific to MacOS, but I am not sure what causes this.

**Comment by alex-hhh** [comment]
This is a problem with Racket, not ActivityLog2, and will be fixed in the next Racket release (I think 8.13)

See https://github.com/racket/gui/issues/325 and https://github.com/racket/gui/pull/326
