### ISSUE TITLE
extract-round: contract violation

### ISSUE THREAD

**Issue by gerhardol** [alex-hhh/ActivityLog2#98]
All activities were imported, but I got the following popup:

![image](https://github.com/alex-hhh/ActivityLog2/assets/6248932/a81a15ee-706f-418a-99fb-353511a5113e)

This is with Forerunner 255 : 18.20 (beta) (or slightly older or latest 17.x) so there may be new .fit changes.

I have not found what activity that caused the error, imported for a couple of weeks.

**Comment by alex-hhh** [comment]
This sounds like a bug, thanks for reporting it.

There should be more information about the error in the log file, `ActivityLogDbg.log`.  On Windows, this should be in the "AppData/Local/ActivityLog" folder under your user directory.   Could you check the log file and see at what stage during the file inport it fails?  The error should also be in that log file, and there should be messages about the import task that was running.

Thanks, Alex.

**Comment by alex-hhh** [comment]
Closing issue, I assume this is fixed by the linked commit, if it is not, let me know and I'll re-open the issue and continue the investigation.
